//! The dashboard's single source of truth for key bindings.
//!
//! Every "normal command" context lists its bindings here once; the keymap
//! lookup ([`super::keymap::action_for_key`]), the command palette
//! ([`super::actions`]), and the help overlay ([`super::keymap::help_rows`])
//! are all derived from this table. Text-entry and PTY contexts (input,
//! filter, comment, planning) handle keys dynamically and keep curated help.
//!
//! `hint: ""` marks a keymap-only binding (hidden from help); `action: None`
//! marks a display-only help row whose keys are handled dynamically (e.g.
//! `1-9` quick-jump).

use crossterm::event::KeyCode;

use crate::tui::Binding;
use crate::tui::chord::KeyChord as K;

use super::actions::Action;

// Canonical context names (must match `super::keymap::context_name`).
const DASHBOARD: &str = "DashboardNormal";
const WORKTREE: &str = "WorktreeNormal";
const TASKS: &str = "TasksNormal";
const DIFF: &str = "DiffNormal";
const PATCH: &str = "Patch";
const PROJECT: &str = "ProjectNormal";

/// Contexts whose keymap/help are registry-driven (everything else is dynamic).
pub const REGISTRY_CONTEXTS: &[&str] = &[DASHBOARD, WORKTREE, TASKS, DIFF, PATCH, PROJECT];

pub const BINDINGS: &[Binding<Action>] = &[
    // ----------------------------------------------------------------- Dashboard
    Binding {
        action: Some(Action::ShowHelp),
        chords: &[K::key('?')],
        hint: "?",
        label: "Show help",
        palette: true,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::Quit),
        chords: &[K::key('q'), K::code(KeyCode::Esc), K::ctrl('c')],
        hint: "q/Esc",
        label: "Quit",
        palette: true,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::Next),
        chords: &[K::key('j'), K::code(KeyCode::Down), K::ctrl('n')],
        hint: "j/↓",
        label: "Next agent",
        palette: false,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::Previous),
        chords: &[K::key('k'), K::code(KeyCode::Up), K::ctrl('p')],
        hint: "k/↑",
        label: "Previous agent",
        palette: false,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::JumpToSelected),
        chords: &[K::code(KeyCode::Enter)],
        hint: "Enter",
        label: "Jump to agent",
        palette: true,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::SwitchTab),
        chords: &[K::code(KeyCode::Tab)],
        hint: "Tab",
        label: "Switch to worktrees",
        palette: true,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::SwitchTabBackward),
        chords: &[K::code(KeyCode::BackTab)],
        hint: "S-Tab",
        label: "Switch view back",
        palette: false,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::SwitchToTasks),
        chords: &[K::key('t')],
        hint: "",
        label: "Tasks tab",
        palette: false,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::JumpToLast),
        chords: &[K::code(KeyCode::Backspace)],
        hint: "Bksp",
        label: "Last agent",
        palette: true,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::PeekSelected),
        chords: &[K::key('p')],
        hint: "p",
        label: "Peek agent (keep popup)",
        palette: true,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::CycleSortMode),
        chords: &[K::key('s')],
        hint: "s",
        label: "Cycle sort mode",
        palette: true,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::ToggleGroupedAgents),
        chords: &[K::key('g')],
        hint: "g",
        label: "Group agents by status",
        palette: true,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::ToggleScopeFilter),
        chords: &[K::key('F')],
        hint: "F",
        label: "Toggle session filter",
        palette: true,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::ToggleStaleFilter),
        chords: &[K::key('f')],
        hint: "f",
        label: "Toggle stale filter",
        palette: true,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::EnterInputMode),
        chords: &[K::key('i')],
        hint: "i",
        label: "Enter input mode",
        palette: true,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::ScrollPreviewUp),
        chords: &[K::ctrl('u')],
        hint: "Ctrl+u",
        label: "Scroll preview up",
        palette: false,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::ScrollPreviewDown),
        chords: &[K::ctrl('d')],
        hint: "Ctrl+d",
        label: "Scroll preview down",
        palette: false,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::IncreasePreviewSize),
        chords: &[K::key('+'), K::key('=')],
        hint: "+",
        label: "Increase preview size",
        palette: false,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::DecreasePreviewSize),
        chords: &[K::key('-'), K::key('_')],
        hint: "-",
        label: "Decrease preview size",
        palette: false,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::LoadWipDiff),
        chords: &[K::key('d')],
        hint: "d",
        label: "View diff",
        palette: true,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::SendCommitDashboard),
        chords: &[K::key('c')],
        hint: "c",
        label: "Commit changes",
        palette: true,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::TriggerMergeDashboard),
        chords: &[K::key('m')],
        hint: "m",
        label: "Merge branch",
        palette: true,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::ShowBaseBranchPicker),
        chords: &[K::key('b')],
        hint: "b",
        label: "Change base branch",
        palette: true,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::OpenPr),
        chords: &[K::key('o')],
        hint: "o",
        label: "Open PR in browser",
        palette: true,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::OpenPrChecks),
        chords: &[K::key('O')],
        hint: "O",
        label: "Open PR checks in browser",
        palette: true,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::KillSelected),
        chords: &[K::key('X')],
        hint: "X",
        label: "Kill agent",
        palette: true,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::RemoveSelectedWorktree),
        chords: &[K::key('r')],
        hint: "r",
        label: "Remove worktree",
        palette: true,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::StartSweep),
        chords: &[K::key('R')],
        hint: "R",
        label: "Sweep cleanup",
        palette: true,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::EnterFilterMode),
        chords: &[K::key('/')],
        hint: "/",
        label: "Filter agents",
        palette: true,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::CycleColorScheme),
        chords: &[K::key('T')],
        hint: "T",
        label: "Cycle theme",
        palette: true,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: Some(Action::ShowCommandPalette),
        chords: &[K::key(':')],
        hint: ":",
        label: "Command palette",
        palette: false,
        contexts: &[DASHBOARD],
    },
    Binding {
        action: None,
        chords: &[],
        hint: "1-9",
        label: "Quick jump",
        palette: false,
        contexts: &[DASHBOARD],
    },
    // ------------------------------------------------------------------ Worktree
    Binding {
        action: Some(Action::ShowHelp),
        chords: &[K::key('?')],
        hint: "?",
        label: "Show help",
        palette: true,
        contexts: &[WORKTREE],
    },
    Binding {
        action: Some(Action::Quit),
        chords: &[K::key('q'), K::code(KeyCode::Esc), K::ctrl('c')],
        hint: "q/Esc",
        label: "Quit",
        palette: true,
        contexts: &[WORKTREE],
    },
    Binding {
        action: Some(Action::SwitchTab),
        chords: &[K::code(KeyCode::Tab)],
        hint: "Tab",
        label: "Switch to agents",
        palette: true,
        contexts: &[WORKTREE],
    },
    Binding {
        action: Some(Action::SwitchTabBackward),
        chords: &[K::code(KeyCode::BackTab)],
        hint: "S-Tab",
        label: "Switch tab back",
        palette: false,
        contexts: &[WORKTREE],
    },
    Binding {
        action: Some(Action::WorktreeNext),
        chords: &[K::key('j'), K::code(KeyCode::Down), K::ctrl('n')],
        hint: "j/↓",
        label: "Next worktree",
        palette: false,
        contexts: &[WORKTREE],
    },
    Binding {
        action: Some(Action::WorktreePrevious),
        chords: &[K::key('k'), K::code(KeyCode::Up), K::ctrl('p')],
        hint: "k/↑",
        label: "Previous worktree",
        palette: false,
        contexts: &[WORKTREE],
    },
    Binding {
        action: Some(Action::SwitchToTasks),
        chords: &[K::key('t')],
        hint: "t",
        label: "Tasks tab",
        palette: false,
        contexts: &[WORKTREE],
    },
    Binding {
        action: Some(Action::JumpToSelectedWorktree),
        chords: &[K::code(KeyCode::Enter)],
        hint: "Enter",
        label: "Jump to worktree",
        palette: true,
        contexts: &[WORKTREE],
    },
    Binding {
        action: Some(Action::OpenPr),
        chords: &[K::key('o')],
        hint: "o",
        label: "Open PR in browser",
        palette: true,
        contexts: &[WORKTREE],
    },
    Binding {
        action: Some(Action::OpenPrChecks),
        chords: &[K::key('O')],
        hint: "O",
        label: "Open PR checks in browser",
        palette: true,
        contexts: &[WORKTREE],
    },
    Binding {
        action: Some(Action::AddWorktree),
        chords: &[K::key('a')],
        hint: "a",
        label: "Add worktree",
        palette: true,
        contexts: &[WORKTREE],
    },
    Binding {
        action: Some(Action::RemoveSelectedWorktree),
        chords: &[K::key('r')],
        hint: "r",
        label: "Remove worktree",
        palette: true,
        contexts: &[WORKTREE],
    },
    Binding {
        action: Some(Action::CloseSelectedWorktreeWindow),
        chords: &[K::key('c')],
        hint: "c",
        label: "Close mux window",
        palette: true,
        contexts: &[WORKTREE],
    },
    Binding {
        action: Some(Action::StartSweep),
        chords: &[K::key('R')],
        hint: "R",
        label: "Sweep cleanup",
        palette: true,
        contexts: &[WORKTREE],
    },
    Binding {
        action: Some(Action::CycleWorktreeSortMode),
        chords: &[K::key('s')],
        hint: "s",
        label: "Cycle sort mode",
        palette: true,
        contexts: &[WORKTREE],
    },
    Binding {
        action: Some(Action::ShowBaseBranchPicker),
        chords: &[K::key('b')],
        hint: "b",
        label: "Change base branch",
        palette: true,
        contexts: &[WORKTREE],
    },
    Binding {
        action: Some(Action::ShowProjectPicker),
        chords: &[K::key('p')],
        hint: "p",
        label: "Switch project",
        palette: true,
        contexts: &[WORKTREE],
    },
    Binding {
        action: Some(Action::EnterFilterMode),
        chords: &[K::key('/')],
        hint: "/",
        label: "Filter worktrees",
        palette: true,
        contexts: &[WORKTREE],
    },
    Binding {
        action: Some(Action::CycleColorScheme),
        chords: &[K::key('T')],
        hint: "T",
        label: "Cycle theme",
        palette: true,
        contexts: &[WORKTREE],
    },
    Binding {
        action: Some(Action::ShowCommandPalette),
        chords: &[K::key(':')],
        hint: ":",
        label: "Command palette",
        palette: false,
        contexts: &[WORKTREE],
    },
    Binding {
        action: None,
        chords: &[],
        hint: "1-9",
        label: "Quick jump",
        palette: false,
        contexts: &[WORKTREE],
    },
    // --------------------------------------------------------------------- Tasks
    Binding {
        action: Some(Action::ShowHelp),
        chords: &[K::key('?')],
        hint: "?",
        label: "Show help",
        palette: false,
        contexts: &[TASKS],
    },
    Binding {
        action: Some(Action::Quit),
        chords: &[K::key('q'), K::code(KeyCode::Esc), K::ctrl('c')],
        hint: "q/Esc",
        label: "Quit",
        palette: false,
        contexts: &[TASKS],
    },
    Binding {
        action: Some(Action::SwitchTab),
        chords: &[K::code(KeyCode::Tab)],
        hint: "Tab",
        label: "Switch tab",
        palette: false,
        contexts: &[TASKS],
    },
    Binding {
        action: Some(Action::SwitchTabBackward),
        chords: &[K::code(KeyCode::BackTab)],
        hint: "S-Tab",
        label: "Switch tab back",
        palette: false,
        contexts: &[TASKS],
    },
    Binding {
        action: Some(Action::TaskNext),
        chords: &[K::key('j'), K::code(KeyCode::Down)],
        hint: "j/↓",
        label: "Next task",
        palette: false,
        contexts: &[TASKS],
    },
    Binding {
        action: Some(Action::TaskPrevious),
        chords: &[K::key('k'), K::code(KeyCode::Up)],
        hint: "k/↑",
        label: "Previous task",
        palette: false,
        contexts: &[TASKS],
    },
    Binding {
        action: Some(Action::TaskAdd),
        chords: &[K::key('a')],
        hint: "a",
        label: "Add task",
        palette: false,
        contexts: &[TASKS],
    },
    Binding {
        action: Some(Action::TaskEdit),
        chords: &[K::key('e')],
        hint: "e",
        label: "Edit task",
        palette: false,
        contexts: &[TASKS],
    },
    Binding {
        action: Some(Action::TaskDelete),
        chords: &[K::key('D')],
        hint: "D",
        label: "Delete task",
        palette: false,
        contexts: &[TASKS],
    },
    Binding {
        action: Some(Action::TaskCycleStatus),
        chords: &[K::key('s')],
        hint: "s",
        label: "Cycle task status",
        palette: false,
        contexts: &[TASKS],
    },
    Binding {
        action: Some(Action::TaskCycleStatusFilter),
        chords: &[K::key('f')],
        hint: "f",
        label: "Cycle status filter",
        palette: false,
        contexts: &[TASKS],
    },
    Binding {
        action: Some(Action::TaskEnterFilter),
        chords: &[K::key('/')],
        hint: "/",
        label: "Filter tasks",
        palette: false,
        contexts: &[TASKS],
    },
    Binding {
        action: Some(Action::TaskReload),
        chords: &[K::key('r')],
        hint: "r",
        label: "Reload",
        palette: false,
        contexts: &[TASKS],
    },
    Binding {
        action: Some(Action::CycleColorScheme),
        chords: &[K::key('T')],
        hint: "T",
        label: "Cycle theme",
        palette: false,
        contexts: &[TASKS],
    },
    // ---------------------------------------------------------------------- Diff
    Binding {
        action: Some(Action::ShowHelp),
        chords: &[K::key('?')],
        hint: "?",
        label: "Show help",
        palette: false,
        contexts: &[DIFF],
    },
    Binding {
        action: Some(Action::CloseDiff),
        chords: &[K::key('q'), K::code(KeyCode::Esc)],
        hint: "q/Esc",
        label: "Close diff",
        palette: true,
        contexts: &[DIFF],
    },
    Binding {
        action: Some(Action::Quit),
        chords: &[K::ctrl('c')],
        hint: "",
        label: "Quit dashboard",
        palette: false,
        contexts: &[DIFF],
    },
    Binding {
        action: Some(Action::ScrollDown),
        chords: &[K::key('j'), K::code(KeyCode::Down)],
        hint: "j/↓",
        label: "Scroll down",
        palette: false,
        contexts: &[DIFF],
    },
    Binding {
        action: Some(Action::ScrollUp),
        chords: &[K::key('k'), K::code(KeyCode::Up)],
        hint: "k/↑",
        label: "Scroll up",
        palette: false,
        contexts: &[DIFF],
    },
    Binding {
        action: Some(Action::ScrollPageDown),
        chords: &[K::code(KeyCode::PageDown), K::ctrl('d')],
        hint: "Ctrl+d",
        label: "Scroll page down",
        palette: false,
        contexts: &[DIFF],
    },
    Binding {
        action: Some(Action::ScrollPageUp),
        chords: &[K::code(KeyCode::PageUp), K::ctrl('u')],
        hint: "Ctrl+u",
        label: "Scroll page up",
        palette: false,
        contexts: &[DIFF],
    },
    Binding {
        action: Some(Action::ToggleDiffType),
        chords: &[K::code(KeyCode::Tab)],
        hint: "Tab",
        label: "Toggle WIP/Review",
        palette: true,
        contexts: &[DIFF],
    },
    Binding {
        action: Some(Action::EnterPatchMode),
        chords: &[K::key('a')],
        hint: "a",
        label: "Enter patch mode (WIP only)",
        palette: false,
        contexts: &[DIFF],
    },
    Binding {
        action: Some(Action::SendCommitDiff),
        chords: &[K::key('c')],
        hint: "c",
        label: "Commit changes",
        palette: true,
        contexts: &[DIFF],
    },
    Binding {
        action: Some(Action::TriggerMergeDiff),
        chords: &[K::key('m')],
        hint: "m",
        label: "Merge branch",
        palette: true,
        contexts: &[DIFF],
    },
    Binding {
        action: Some(Action::ShowCommandPalette),
        chords: &[K::key(':')],
        hint: ":",
        label: "Command palette",
        palette: false,
        contexts: &[DIFF],
    },
    // --------------------------------------------------------------------- Patch
    Binding {
        action: Some(Action::ShowHelp),
        chords: &[K::key('?')],
        hint: "?",
        label: "Show help",
        palette: false,
        contexts: &[PATCH],
    },
    Binding {
        action: Some(Action::Quit),
        chords: &[K::ctrl('c')],
        hint: "",
        label: "Quit dashboard",
        palette: false,
        contexts: &[PATCH],
    },
    Binding {
        action: Some(Action::StageAndNext),
        chords: &[K::key('y')],
        hint: "y",
        label: "Stage hunk",
        palette: true,
        contexts: &[PATCH],
    },
    Binding {
        action: Some(Action::SkipHunk),
        chords: &[K::key('n')],
        hint: "n",
        label: "Skip hunk",
        palette: true,
        contexts: &[PATCH],
    },
    Binding {
        action: Some(Action::UndoStagedHunk),
        chords: &[K::key('u')],
        hint: "u",
        label: "Undo last staged",
        palette: true,
        contexts: &[PATCH],
    },
    Binding {
        action: Some(Action::SplitHunk),
        chords: &[K::key('s')],
        hint: "s",
        label: "Split hunk",
        palette: true,
        contexts: &[PATCH],
    },
    Binding {
        action: Some(Action::StartComment),
        chords: &[K::key('o')],
        hint: "o",
        label: "Add comment",
        palette: true,
        contexts: &[PATCH],
    },
    Binding {
        action: Some(Action::PrevHunk),
        chords: &[K::key('k'), K::code(KeyCode::Up)],
        hint: "k/↑",
        label: "Previous hunk",
        palette: false,
        contexts: &[PATCH],
    },
    Binding {
        action: Some(Action::NextHunk),
        chords: &[K::key('j'), K::code(KeyCode::Down)],
        hint: "j/↓",
        label: "Next hunk",
        palette: false,
        contexts: &[PATCH],
    },
    Binding {
        action: Some(Action::ScrollPageDown),
        chords: &[K::ctrl('d')],
        hint: "Ctrl+d",
        label: "Scroll hunk down",
        palette: false,
        contexts: &[PATCH],
    },
    Binding {
        action: Some(Action::ScrollPageUp),
        chords: &[K::ctrl('u')],
        hint: "Ctrl+u",
        label: "Scroll hunk up",
        palette: false,
        contexts: &[PATCH],
    },
    Binding {
        action: Some(Action::SendCommitDiff),
        chords: &[K::key('c')],
        hint: "c",
        label: "Commit changes",
        palette: true,
        contexts: &[PATCH],
    },
    Binding {
        action: Some(Action::TriggerMergeDiff),
        chords: &[K::key('m')],
        hint: "m",
        label: "Merge branch",
        palette: true,
        contexts: &[PATCH],
    },
    Binding {
        action: Some(Action::ExitPatchMode),
        chords: &[K::key('q'), K::code(KeyCode::Esc)],
        hint: "q/Esc",
        label: "Exit patch mode",
        palette: true,
        contexts: &[PATCH],
    },
    Binding {
        action: Some(Action::ShowCommandPalette),
        chords: &[K::key(':')],
        hint: ":",
        label: "Command palette",
        palette: false,
        contexts: &[PATCH],
    },
    // ------------------------------------------------------------------- Project
    Binding {
        action: Some(Action::ShowHelp),
        chords: &[K::key('?')],
        hint: "?",
        label: "Show help",
        palette: false,
        contexts: &[PROJECT],
    },
    Binding {
        action: Some(Action::Quit),
        chords: &[K::key('q'), K::code(KeyCode::Esc), K::ctrl('c')],
        hint: "q/Esc",
        label: "Quit",
        palette: false,
        contexts: &[PROJECT],
    },
    Binding {
        action: Some(Action::SwitchTab),
        chords: &[K::code(KeyCode::Tab)],
        hint: "Tab",
        label: "Switch tab",
        palette: false,
        contexts: &[PROJECT],
    },
    Binding {
        action: Some(Action::SwitchTabBackward),
        chords: &[K::code(KeyCode::BackTab)],
        hint: "S-Tab",
        label: "Switch tab back",
        palette: false,
        contexts: &[PROJECT],
    },
    Binding {
        action: Some(Action::CycleColorScheme),
        chords: &[K::key('T')],
        hint: "T",
        label: "Cycle theme",
        palette: false,
        contexts: &[PROJECT],
    },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn no_binding_conflicts() {
        crate::tui::binding::assert_no_conflicts(BINDINGS);
    }
}
