import os
import shlex
from pathlib import Path

import pytest

from .conftest import (
    TmuxEnvironment,
    create_commit,
    get_window_name,
    get_worktree_path,
    poll_until,
    run_workmux_add,
    run_workmux_command,
    write_workmux_config,
    write_global_workmux_config,
)


def install_fake_agent(env: TmuxEnvironment, name: str, script_body: str) -> Path:
    """Creates a fake agent command in PATH so tmux panes can invoke it."""
    bin_dir = env.tmp_path / "agents-bin"
    bin_dir.mkdir(exist_ok=True)
    script_path = bin_dir / name
    script_path.write_text(script_body)
    script_path.chmod(0o755)

    new_path = f"{bin_dir}:{env.env.get('PATH', '')}"
    env.env["PATH"] = new_path
    env.tmux(["set-environment", "-g", "PATH", new_path])
    return script_path


def add_branch_and_get_worktree(
    env: TmuxEnvironment,
    workmux_exe_path: Path,
    repo_path: Path,
    branch_name: str,
    extra_args: str = "",
    command_target: str | None = None,
    **kwargs,
) -> Path:
    """Run `workmux add` and return the new worktree path."""
    target = command_target or branch_name
    command = f"add {target}"
    if extra_args:
        command = f"{command} {extra_args}"

    run_workmux_command(
        env,
        workmux_exe_path,
        repo_path,
        command,
        **kwargs,
    )

    worktree_path = get_worktree_path(repo_path, branch_name)
    assert worktree_path.is_dir()
    return worktree_path


def assert_window_exists(env: TmuxEnvironment, window_name: str) -> None:
    """Ensure a tmux window with the provided name exists."""
    result = env.tmux(["list-windows", "-F", "#{window_name}"])
    existing_windows = [w for w in result.stdout.strip().split("\n") if w]
    assert (
        window_name in existing_windows
    ), f"Window {window_name!r} not found. Existing: {existing_windows!r}"


def wait_for_pane_output(
    env: TmuxEnvironment, window_name: str, text: str, timeout: float = 2.0
) -> None:
    """Poll until the specified text appears in the pane."""

    def _has_output() -> bool:
        capture_result = env.tmux(["capture-pane", "-p", "-t", window_name])
        return text in capture_result.stdout

    assert poll_until(_has_output, timeout=timeout), (
        f"Expected output {text!r} not found in window {window_name!r}"
    )


def prompt_file_for_branch(branch_name: str) -> Path:
    """Return the path to the prompt file for the given branch."""
    return Path(f"/tmp/workmux-prompt-{branch_name}.md")


def assert_prompt_file_contents(branch_name: str, expected_text: str) -> None:
    """Assert that a prompt file exists for the branch and matches the expected text."""
    prompt_file = prompt_file_for_branch(branch_name)
    assert prompt_file.exists(), f"Prompt file not found at {prompt_file}"
    assert prompt_file.read_text() == expected_text


def file_for_commit(worktree_path: Path, commit_message: str) -> Path:
    """Return the expected file path generated by create_commit for a message."""
    sanitized = commit_message.replace(" ", "_").replace(":", "")
    return worktree_path / f"file_for_{sanitized}.txt"


def assert_copied_file(
    worktree_path: Path, relative_path: str, expected_text: str | None = None
) -> Path:
    """Assert that a copied file exists in the worktree and is not a symlink."""
    file_path = worktree_path / relative_path
    assert file_path.exists(), f"Expected copied file {relative_path} to exist"
    assert (
        not file_path.is_symlink()
    ), f"Expected {relative_path} to be a regular file, but found a symlink"
    if expected_text is not None:
        assert file_path.read_text() == expected_text
    return file_path


def assert_symlink_to(worktree_path: Path, relative_path: str) -> Path:
    """Assert that a symlink exists in the worktree and return the path."""
    symlink_path = worktree_path / relative_path
    assert symlink_path.exists(), f"Expected symlink {relative_path} to exist"
    assert symlink_path.is_symlink(), f"Expected {relative_path} to be a symlink"
    return symlink_path


def configure_default_shell(shell: str | None = None) -> list[list[str]]:
    """Return tmux commands that configure the default shell for panes."""
    shell_path = shell or os.environ.get("SHELL", "/bin/zsh")
    return [["set-option", "-g", "default-shell", shell_path]]


def test_add_creates_worktree(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies that `workmux add` creates a git worktree."""
    env = isolated_tmux_server
    branch_name = "feature-worktree"

    write_workmux_config(repo_path)

    worktree_path = add_branch_and_get_worktree(
        env, workmux_exe_path, repo_path, branch_name
    )

    # Verify worktree in git's state
    worktree_list_result = env.run_command(["git", "worktree", "list"])
    assert branch_name in worktree_list_result.stdout

    # Verify worktree directory exists
    assert worktree_path.is_dir()


def test_add_creates_tmux_window(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies that `workmux add` creates a tmux window with the correct name."""
    env = isolated_tmux_server
    branch_name = "feature-window"
    window_name = get_window_name(branch_name)

    write_workmux_config(repo_path)

    add_branch_and_get_worktree(env, workmux_exe_path, repo_path, branch_name)

    assert_window_exists(env, window_name)


def test_add_inline_prompt_injects_into_claude(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Inline prompts should be written to PROMPT.md and passed to claude via command substitution."""
    env = isolated_tmux_server
    branch_name = "feature-inline-prompt"
    prompt_text = "Implement inline prompt"
    output_filename = "claude_prompt.txt"

    fake_claude_path = install_fake_agent(
        env,
        "claude",
        f"""#!/bin/sh
# Debug: log all arguments
echo "ARGS: $@" > debug_args.txt
echo "ARG1: $1" >> debug_args.txt
echo "ARG2: $2" >> debug_args.txt

set -e
# The implementation calls: claude "$(cat PROMPT.md)"
# So we expect the prompt content as the first argument
printf '%s' "$1" > "{output_filename}"
""",
    )

    # Use absolute path to ensure we use the fake claude
    write_workmux_config(repo_path, panes=[{"command": str(fake_claude_path)}])

    worktree_path = add_branch_and_get_worktree(
        env,
        workmux_exe_path,
        repo_path,
        branch_name,
        extra_args=f"--prompt {shlex.quote(prompt_text)}",
    )

    # Prompt file is now written to /tmp instead of the worktree
    assert_prompt_file_contents(branch_name, prompt_text)

    agent_output = worktree_path / output_filename
    debug_output = worktree_path / "debug_args.txt"

    def agent_wrote_prompt():
        return agent_output.exists()

    if not poll_until(agent_wrote_prompt, timeout=2.0):
        # Print debug info if test fails
        print(f"\nWorktree path: {worktree_path}")
        print(f"Files in worktree: {list(worktree_path.iterdir())}")
        if debug_output.exists():
            print(f"\nDebug output:\n{debug_output.read_text()}")
        else:
            print("\nDebug output file not found - script never executed")

        # Check tmux pane output

        pane_content = env.tmux(["capture-pane", "-t", f"=wm-{branch_name}.0", "-p"])
        print(f"\nTmux pane content:\n{pane_content.stdout}")

        assert False, "Agent output not found"

    assert agent_output.read_text() == prompt_text


def test_add_prompt_file_injects_into_gemini(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Prompt file flag should populate PROMPT.md and pass it to gemini via command substitution."""
    env = isolated_tmux_server
    branch_name = "feature-file-prompt"
    prompt_source = repo_path / "prompt_source.txt"
    prompt_source.write_text("File-based instructions")
    output_filename = "gemini_prompt.txt"

    fake_gemini_path = install_fake_agent(
        env,
        "gemini",
        f"""#!/bin/sh
set -e
# The implementation calls: gemini -i "$(cat PROMPT.md)"
# So we expect -i flag first, then the prompt content as the second argument
if [ "$1" != "-i" ]; then
    echo "Expected -i flag first" >&2
    exit 1
fi
printf '%s' "$2" > "{output_filename}"
""",
    )

    # Use absolute path to ensure we use the fake gemini
    write_workmux_config(
        repo_path, agent="gemini", panes=[{"command": str(fake_gemini_path)}]
    )

    worktree_path = add_branch_and_get_worktree(
        env,
        workmux_exe_path,
        repo_path,
        branch_name,
        extra_args=f"--prompt-file {shlex.quote(str(prompt_source))}",
    )

    # Prompt file is now written to /tmp instead of the worktree
    assert_prompt_file_contents(branch_name, prompt_source.read_text())

    agent_output = worktree_path / output_filename

    def agent_wrote_prompt():
        return agent_output.exists()

    assert poll_until(agent_wrote_prompt, timeout=2.0), (
        "Prompt content was not passed to gemini"
    )
    assert agent_output.read_text() == prompt_source.read_text()


def test_add_uses_agent_from_config(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """The <agent> placeholder should use the agent configured in .workmux.yaml when --agent is not passed."""
    env = isolated_tmux_server
    branch_name = "feature-config-agent"
    prompt_text = "Using configured agent"
    output_filename = "agent_output.txt"

    # Install fake gemini agent
    install_fake_agent(
        env,
        "gemini",
        f"""#!/bin/sh
set -e
# Gemini gets a -i flag
printf '%s' "$2" > "{output_filename}"
""",
    )

    # Configure .workmux.yaml to use gemini with <agent> placeholder
    write_workmux_config(repo_path, agent="gemini", panes=[{"command": "<agent>"}])

    # Run 'add' WITHOUT --agent flag, should use gemini from config
    worktree_path = add_branch_and_get_worktree(
        env,
        workmux_exe_path,
        repo_path,
        branch_name,
        extra_args=f"--prompt {shlex.quote(prompt_text)}",
    )

    agent_output = worktree_path / output_filename

    def agent_ran():
        return agent_output.exists()

    assert poll_until(agent_ran, timeout=2.0), "Configured agent did not run"
    assert agent_output.read_text() == prompt_text


def test_add_with_agent_flag_overrides_default(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """The --agent flag should override the default agent and inject prompts correctly."""
    env = isolated_tmux_server
    branch_name = "feature-agent-override"
    prompt_text = "This is for the override agent"
    output_filename = "agent_output.txt"

    # Create two fake agents: a default one and the one we'll specify via the flag.
    # Default agent (claude)
    install_fake_agent(
        env,
        "claude",
        "#!/bin/sh\necho 'default agent ran' > default_agent.txt",
    )

    # Override agent (gemini)
    install_fake_agent(
        env,
        "gemini",
        f"""#!/bin/sh
# Gemini gets a -i flag
printf '%s' "$2" > "{output_filename}"
""",
    )

    # Configure workmux to use <agent> placeholder. The default should be 'claude'.
    write_workmux_config(repo_path, panes=[{"command": "<agent>"}])

    # Run 'add' with the --agent flag to override the default
    worktree_path = add_branch_and_get_worktree(
        env,
        workmux_exe_path,
        repo_path,
        branch_name,
        extra_args=f"--agent gemini --prompt {shlex.quote(prompt_text)}",
    )

    agent_output = worktree_path / output_filename
    default_agent_output = worktree_path / "default_agent.txt"

    def override_agent_ran():
        return agent_output.exists()

    assert poll_until(override_agent_ran, timeout=2.0), "Override agent did not run"
    assert not default_agent_output.exists(), "Default agent should not have run"
    assert agent_output.read_text() == prompt_text


def test_add_executes_post_create_hooks(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies that `workmux add` executes post_create hooks in the worktree directory."""
    env = isolated_tmux_server
    branch_name = "feature-hooks"
    hook_file = "hook_was_executed.txt"

    write_workmux_config(repo_path, post_create=[f"touch {hook_file}"])

    worktree_path = add_branch_and_get_worktree(
        env, workmux_exe_path, repo_path, branch_name
    )

    # Verify hook file was created in the worktree directory
    assert (worktree_path / hook_file).exists()


def test_add_without_prompt_skips_prompt_file(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Worktrees created without prompt flags should not create PROMPT.md."""
    env = isolated_tmux_server
    branch_name = "feature-no-prompt"

    write_workmux_config(repo_path, panes=[])

    worktree_path = add_branch_and_get_worktree(
        env, workmux_exe_path, repo_path, branch_name
    )
    # Verify no PROMPT.md in worktree
    assert not (worktree_path / "PROMPT.md").exists()
    # Verify no prompt file in /tmp either
    assert not prompt_file_for_branch(branch_name).exists()


def test_add_can_skip_post_create_hooks(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """`workmux add --no-hooks` should not run configured post_create hooks."""
    env = isolated_tmux_server
    branch_name = "feature-skip-hooks"
    hook_file = "hook_should_not_exist.txt"

    write_workmux_config(repo_path, post_create=[f"touch {hook_file}"])

    worktree_path = add_branch_and_get_worktree(
        env,
        workmux_exe_path,
        repo_path,
        branch_name,
        extra_args="--no-hooks",
    )

    assert not (worktree_path / hook_file).exists()


def test_add_executes_pane_commands(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies that `workmux add` executes commands in configured panes."""
    env = isolated_tmux_server
    branch_name = "feature-panes"
    window_name = get_window_name(branch_name)
    expected_output = "test pane command output"

    write_workmux_config(
        repo_path, panes=[{"command": f"echo '{expected_output}'; sleep 0.5"}]
    )

    add_branch_and_get_worktree(env, workmux_exe_path, repo_path, branch_name)

    wait_for_pane_output(env, window_name, expected_output)


def test_add_can_skip_pane_commands(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """`workmux add --no-pane-cmds` should create panes without running commands."""
    env = isolated_tmux_server
    branch_name = "feature-skip-pane-cmds"
    marker_file = "pane_command_output.txt"

    write_workmux_config(repo_path, panes=[{"command": f"touch {marker_file}"}])

    worktree_path = add_branch_and_get_worktree(
        env,
        workmux_exe_path,
        repo_path,
        branch_name,
        extra_args="--no-pane-cmds",
    )

    assert not (worktree_path / marker_file).exists()


def test_add_copies_directories(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies that directory copy rules replicate nested contents into the worktree."""
    env = isolated_tmux_server
    branch_name = "feature-copy-dir"
    shared_dir = repo_path / "shared-config"
    nested_dir = shared_dir / "nested"

    nested_dir.mkdir(parents=True)
    (shared_dir / "root.txt").write_text("root-level")
    (nested_dir / "child.txt").write_text("nested-level")

    write_workmux_config(repo_path, files={"copy": ["shared-config"]})

    worktree_path = add_branch_and_get_worktree(
        env, workmux_exe_path, repo_path, branch_name
    )
    copied_dir = worktree_path / "shared-config"

    assert copied_dir.is_dir()
    assert (copied_dir / "root.txt").read_text() == "root-level"
    assert (copied_dir / "nested" / "child.txt").read_text() == "nested-level"


def test_add_can_skip_file_operations(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """`workmux add --no-file-ops` should not perform configured copy/symlink actions."""
    env = isolated_tmux_server
    branch_name = "feature-skip-file-ops"
    shared_dir = repo_path / "skip-shared"
    shared_dir.mkdir()
    (shared_dir / "data.txt").write_text("copy-me")

    write_workmux_config(repo_path, files={"copy": ["skip-shared"]})

    worktree_path = add_branch_and_get_worktree(
        env,
        workmux_exe_path,
        repo_path,
        branch_name,
        extra_args="--no-file-ops",
    )

    assert not (worktree_path / "skip-shared").exists()


def test_add_sources_shell_rc_files(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies that shell rc files (.zshrc) are sourced and aliases work in pane commands."""
    env = isolated_tmux_server
    branch_name = "feature-aliases"
    window_name = get_window_name(branch_name)
    alias_output = "custom_alias_worked_correctly"

    # The environment now provides an isolated HOME directory.
    # Write the .zshrc file there.
    zshrc_content = f"""
# Test alias
alias testcmd='echo "{alias_output}"'
"""
    (env.home_path / ".zshrc").write_text(zshrc_content)

    write_workmux_config(repo_path, panes=[{"command": "testcmd; sleep 0.5"}])

    pre_cmds = configure_default_shell()

    add_branch_and_get_worktree(
        env, workmux_exe_path, repo_path, branch_name, pre_run_tmux_cmds=pre_cmds
    )

    wait_for_pane_output(
        env,
        window_name,
        alias_output,
        timeout=2.0,
    )


def test_agent_placeholder_respects_shell_aliases(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies that the <agent> placeholder triggers aliases defined in shell rc files."""
    env = isolated_tmux_server
    branch_name = "feature-agent-alias"
    marker_content = "alias_was_expanded"

    (env.home_path / ".zshrc").write_text(
        """
alias claude='claude --aliased'
""".strip()
        + "\n"
    )

    install_fake_agent(
        env,
        "claude",
        f"""#!/bin/sh
set -e
for arg in "$@"; do
  if [ "$arg" = "--aliased" ]; then
    echo "{marker_content}" > alias_marker.txt
    exit 0
  fi
done
echo "Alias flag not found" > alias_marker.txt
exit 1
""",
    )

    write_workmux_config(repo_path, agent="claude", panes=[{"command": "<agent>"}])

    pre_cmds = configure_default_shell()

    worktree_path = add_branch_and_get_worktree(
        env, workmux_exe_path, repo_path, branch_name, pre_run_tmux_cmds=pre_cmds
    )
    marker_file = worktree_path / "alias_marker.txt"

    def alias_marker_exists():
        return marker_file.exists()

    assert poll_until(alias_marker_exists, timeout=2.0), (
        "Agent marker file missing; alias likely not executed."
    )
    assert (
        marker_file.read_text().strip() == marker_content
    ), "Alias marker content incorrect; alias flag not detected."


def test_project_config_overrides_global_config(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Project-level settings should override conflicting global settings."""
    env = isolated_tmux_server
    branch_name = "feature-project-overrides"
    global_prefix = "global-"
    project_prefix = "project-"

    write_global_workmux_config(env, window_prefix=global_prefix)
    write_workmux_config(repo_path, window_prefix=project_prefix)

    add_branch_and_get_worktree(env, workmux_exe_path, repo_path, branch_name)

    project_window = f"{project_prefix}{branch_name}"
    assert_window_exists(env, project_window)

    list_windows_result = env.tmux(["list-windows", "-F", "#{window_name}"])
    existing_windows = list_windows_result.stdout.strip().split("\n")
    assert f"{global_prefix}{branch_name}" not in existing_windows


def test_global_config_used_when_project_config_absent(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Global config should be respected even if the repository lacks .workmux.yaml."""
    env = isolated_tmux_server
    branch_name = "feature-global-only"
    hook_file = "global_only_hook.txt"

    write_global_workmux_config(env, post_create=[f"touch {hook_file}"])

    worktree_path = add_branch_and_get_worktree(
        env, workmux_exe_path, repo_path, branch_name
    )
    assert (worktree_path / hook_file).exists()


def test_global_placeholder_merges_post_create_commands(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """The '<global>' placeholder should expand to global post_create commands."""
    env = isolated_tmux_server
    branch_name = "feature-global-hooks"
    global_hook = "created_from_global.txt"
    before_hook = "project_before.txt"
    after_hook = "project_after.txt"

    write_global_workmux_config(env, post_create=[f"touch {global_hook}"])
    write_workmux_config(
        repo_path,
        post_create=[f"touch {before_hook}", "<global>", f"touch {after_hook}"],
    )

    worktree_dir = add_branch_and_get_worktree(
        env, workmux_exe_path, repo_path, branch_name
    )
    assert (worktree_dir / before_hook).exists()
    assert (worktree_dir / global_hook).exists()
    assert (worktree_dir / after_hook).exists()


def test_global_placeholder_merges_file_operations(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """The '<global>' placeholder should merge copy and symlink file operations."""
    env = isolated_tmux_server
    branch_name = "feature-global-files"

    # Create files/directories that will be copied or symlinked.
    global_copy = repo_path / "global.env"
    project_copy = repo_path / "project.env"
    global_copy.write_text("GLOBAL")
    project_copy.write_text("PROJECT")

    global_dir = repo_path / "global_cache"
    project_dir = repo_path / "project_cache"
    global_dir.mkdir()
    (global_dir / "shared.txt").write_text("global data")
    project_dir.mkdir()
    (project_dir / "local.txt").write_text("project data")

    env.run_command(
        ["git", "add", "global.env", "project.env", "global_cache", "project_cache"],
        cwd=repo_path,
    )
    env.run_command(
        ["git", "commit", "-m", "Add files for global placeholder tests"], cwd=repo_path
    )

    write_global_workmux_config(
        env,
        files={"copy": ["global.env"], "symlink": ["global_cache"]},
    )
    write_workmux_config(
        repo_path,
        files={
            "copy": ["<global>", "project.env"],
            "symlink": ["<global>", "project_cache"],
        },
    )

    worktree_dir = add_branch_and_get_worktree(
        env, workmux_exe_path, repo_path, branch_name
    )
    symlinked_global = assert_symlink_to(worktree_dir, "global_cache")
    symlinked_project = assert_symlink_to(worktree_dir, "project_cache")
    assert (symlinked_global / "shared.txt").read_text() == "global data"
    assert (symlinked_project / "local.txt").read_text() == "project data"

    assert_copied_file(worktree_dir, "global.env", "GLOBAL")
    assert_copied_file(worktree_dir, "project.env", "PROJECT")


def test_global_placeholder_only_merges_specific_file_lists(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """`<global>` can merge copy patterns while symlink patterns fully override."""
    env = isolated_tmux_server
    branch_name = "feature-partial-file-merge"

    ignored_files = [
        "global_copy.txt",
        "project_copy.txt",
        "global_symlink_dir/",
        "project_symlink_dir/",
    ]
    with (repo_path / ".gitignore").open("a") as gitignore:
        for entry in ignored_files:
            gitignore.write(f"{entry}\n")

    (repo_path / "global_copy.txt").write_text("global copy")
    (repo_path / "project_copy.txt").write_text("project copy")
    global_symlink_dir = repo_path / "global_symlink_dir"
    global_symlink_dir.mkdir()
    (global_symlink_dir / "global.txt").write_text("global data")
    project_symlink_dir = repo_path / "project_symlink_dir"
    project_symlink_dir.mkdir()
    (project_symlink_dir / "project.txt").write_text("project data")

    write_global_workmux_config(
        env,
        files={"copy": ["global_copy.txt"], "symlink": ["global_symlink_dir"]},
    )
    write_workmux_config(
        repo_path,
        files={
            "copy": ["<global>", "project_copy.txt"],
            "symlink": ["project_symlink_dir"],
        },
    )

    worktree_dir = add_branch_and_get_worktree(
        env, workmux_exe_path, repo_path, branch_name
    )
    assert_copied_file(worktree_dir, "global_copy.txt")
    assert_copied_file(worktree_dir, "project_copy.txt")

    assert_symlink_to(worktree_dir, "project_symlink_dir")
    assert not (worktree_dir / "global_symlink_dir").exists()


def test_project_empty_file_lists_override_global_lists(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Explicit empty lists suppress the corresponding global file operations."""
    env = isolated_tmux_server
    branch_name = "feature-empty-file-override"

    ignored_files = [
        "global_only.env",
        "global_shared_dir/",
    ]
    with (repo_path / ".gitignore").open("a") as gitignore:
        for entry in ignored_files:
            gitignore.write(f"{entry}\n")

    (repo_path / "global_only.env").write_text("SECRET=1")
    global_shared_dir = repo_path / "global_shared_dir"
    global_shared_dir.mkdir()
    (global_shared_dir / "package.json").write_text('{"name":"demo"}')

    write_global_workmux_config(
        env,
        files={"copy": ["global_only.env"], "symlink": ["global_shared_dir"]},
    )
    write_workmux_config(
        repo_path,
        files={"copy": [], "symlink": []},
    )

    worktree_dir = add_branch_and_get_worktree(
        env, workmux_exe_path, repo_path, branch_name
    )
    assert not (worktree_dir / "global_only.env").exists()
    assert not (worktree_dir / "global_shared_dir").exists()


def test_project_panes_replace_global_panes(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Project panes should completely replace global panes (no merging)."""
    env = isolated_tmux_server
    branch_name = "feature-pane-override"
    window_name = get_window_name(branch_name)
    global_output = "GLOBAL_PANE_OUTPUT"
    project_output = "PROJECT_PANE_OUTPUT"

    write_global_workmux_config(
        env, panes=[{"command": f"echo '{global_output}'; sleep 0.5"}]
    )
    write_workmux_config(
        repo_path, panes=[{"command": f"echo '{project_output}'; sleep 0.5"}]
    )

    add_branch_and_get_worktree(env, workmux_exe_path, repo_path, branch_name)

    wait_for_pane_output(env, window_name, project_output)

    capture_result = env.tmux(["capture-pane", "-p", "-t", window_name])
    assert global_output not in capture_result.stdout


def test_add_from_specific_branch(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies that `workmux add --base` creates a worktree from a specific branch."""
    env = isolated_tmux_server
    new_branch = "feature-from-base"

    write_workmux_config(repo_path)

    # Create a commit on the current branch
    create_commit(env, repo_path, "Add base file")

    # Get current branch name
    result = env.run_command(["git", "branch", "--show-current"], cwd=repo_path)
    base_branch = result.stdout.strip()

    # Run workmux add with --base flag
    worktree_path = add_branch_and_get_worktree(
        env,
        workmux_exe_path,
        repo_path,
        new_branch,
        extra_args=f"--base {base_branch}",
    )

    # Verify the new branch contains the file from base branch
    expected_file = file_for_commit(worktree_path, "Add base file")
    assert expected_file.exists()

    # Verify tmux window was created
    window_name = get_window_name(new_branch)
    assert_window_exists(env, window_name)


def test_add_defaults_to_current_branch(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """`workmux add` without --base should inherit from the current branch."""
    env = isolated_tmux_server
    base_branch = "feature-default-base"
    stacked_branch = "feature-default-child"
    commit_message = "Stack default change"

    write_workmux_config(repo_path)

    env.run_command(["git", "checkout", "-b", base_branch], cwd=repo_path)
    create_commit(env, repo_path, commit_message)

    stacked_worktree = add_branch_and_get_worktree(
        env, workmux_exe_path, repo_path, stacked_branch
    )
    expected_file = file_for_commit(stacked_worktree, commit_message)
    assert expected_file.exists()

    window_name = get_window_name(stacked_branch)
    assert_window_exists(env, window_name)


def test_add_from_current_branch_flag(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """`workmux add --from-current` should base new branches on the active branch."""
    env = isolated_tmux_server
    base_branch = "feature-stack-base"
    stacked_branch = "feature-stack-child"
    commit_message = "Stack base change"

    write_workmux_config(repo_path)

    # Start a new branch and add a commit that the stacked branch should inherit.
    env.run_command(["git", "checkout", "-b", base_branch], cwd=repo_path)
    create_commit(env, repo_path, commit_message)

    stacked_worktree = add_branch_and_get_worktree(
        env,
        workmux_exe_path,
        repo_path,
        stacked_branch,
        extra_args="--from-current",
    )

    expected_file = file_for_commit(stacked_worktree, commit_message)
    assert expected_file.exists()

    window_name = get_window_name(stacked_branch)
    assert_window_exists(env, window_name)


def test_add_errors_when_detached_head_without_base(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Detached HEAD states should require --base."""
    env = isolated_tmux_server
    branch_name = "feature-detached-head"

    write_workmux_config(repo_path)

    head_sha = env.run_command(
        ["git", "rev-parse", "HEAD"], cwd=repo_path
    ).stdout.strip()
    env.run_command(["git", "checkout", head_sha], cwd=repo_path)

    result = run_workmux_command(
        env, workmux_exe_path, repo_path, f"add {branch_name}", expect_fail=True
    )

    assert "detached HEAD" in result.stderr


def test_add_allows_detached_head_with_explicit_base(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Detached HEAD states can still create worktrees when --base is provided."""
    env = isolated_tmux_server
    branch_name = "feature-detached-head-base"
    commit_message = "Detached baseline"

    write_workmux_config(repo_path)
    create_commit(env, repo_path, commit_message)

    head_sha = env.run_command(
        ["git", "rev-parse", "HEAD"], cwd=repo_path
    ).stdout.strip()
    env.run_command(["git", "checkout", head_sha], cwd=repo_path)

    worktree_path = add_branch_and_get_worktree(
        env,
        workmux_exe_path,
        repo_path,
        branch_name,
        extra_args="--base main",
    )

    expected_file = file_for_commit(worktree_path, commit_message)
    assert expected_file.exists()


def test_add_reuses_existing_branch(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies that `workmux add` reuses an existing branch instead of creating a new one."""
    env = isolated_tmux_server
    branch_name = "feature-existing-branch"
    commit_message = "Existing branch changes"

    write_workmux_config(repo_path)

    # Remember the default branch so we can switch back after preparing the feature branch
    current_branch_result = env.run_command(
        ["git", "branch", "--show-current"], cwd=repo_path
    )
    default_branch = current_branch_result.stdout.strip()

    # Create and populate an existing branch
    env.run_command(["git", "checkout", "-b", branch_name], cwd=repo_path)
    create_commit(env, repo_path, commit_message)
    branch_head = env.run_command(
        ["git", "rev-parse", "HEAD"], cwd=repo_path
    ).stdout.strip()

    # Switch back to the default branch so workmux add runs from a typical state
    env.run_command(["git", "checkout", default_branch], cwd=repo_path)

    worktree_path = add_branch_and_get_worktree(
        env, workmux_exe_path, repo_path, branch_name
    )
    expected_file = file_for_commit(worktree_path, commit_message)
    assert expected_file.exists()
    assert expected_file.read_text() == f"content for {commit_message}"

    # The branch should still point to the commit we created earlier
    branch_tip = env.run_command(
        ["git", "rev-parse", branch_name], cwd=repo_path
    ).stdout.strip()
    assert branch_tip == branch_head


def test_add_from_remote_branch(
    isolated_tmux_server: TmuxEnvironment,
    workmux_exe_path: Path,
    repo_path: Path,
    remote_repo_path: Path,
):
    """When the branch exists only on the remote, workmux add should fetch and track it."""
    env = isolated_tmux_server
    remote_branch_path = "feature/remote-pr"
    remote_ref = f"origin/{remote_branch_path}"
    commit_message = "Remote PR work"

    write_workmux_config(repo_path)

    # Wire up the repo to a bare remote and push the default branch.
    env.run_command(
        ["git", "remote", "add", "origin", str(remote_repo_path)], cwd=repo_path
    )
    env.run_command(["git", "push", "-u", "origin", "main"], cwd=repo_path)

    # Create a branch with commits and push it to the remote.
    env.run_command(["git", "checkout", "-b", remote_branch_path], cwd=repo_path)
    create_commit(env, repo_path, commit_message)
    remote_tip = env.run_command(
        ["git", "rev-parse", remote_branch_path], cwd=repo_path
    ).stdout.strip()
    env.run_command(["git", "push", "-u", "origin", remote_branch_path], cwd=repo_path)

    # Remove the local branch and remote-tracking ref so the branch only exists on the remote.
    env.run_command(["git", "checkout", "main"], cwd=repo_path)
    env.run_command(["git", "branch", "-D", remote_branch_path], cwd=repo_path)
    env.run_command(
        ["git", "update-ref", "-d", f"refs/remotes/{remote_ref}"],
        cwd=repo_path,
    )

    worktree_path = add_branch_and_get_worktree(
        env,
        workmux_exe_path,
        repo_path,
        remote_branch_path,
        command_target=remote_ref,
    )
    expected_file = file_for_commit(worktree_path, commit_message)
    assert expected_file.exists()
    assert expected_file.read_text() == f"content for {commit_message}"

    # Local branch should point to the remote commit and track origin/<branch_name>.
    branch_tip = env.run_command(
        ["git", "rev-parse", remote_branch_path], cwd=repo_path
    ).stdout.strip()
    assert branch_tip == remote_tip

    upstream_tip = env.run_command(
        ["git", "rev-parse", f"{remote_branch_path}@{{upstream}}"], cwd=repo_path
    ).stdout.strip()
    assert upstream_tip == remote_tip

    origin_tip = env.run_command(
        ["git", "rev-parse", remote_ref], cwd=repo_path
    ).stdout.strip()
    assert origin_tip == remote_tip


def test_add_fails_when_worktree_exists(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies that `workmux add` fails with a clear message if the worktree already exists."""
    env = isolated_tmux_server
    branch_name = "feature-existing-worktree"
    existing_worktree_path = repo_path.parent / "existing_worktree_dir"

    write_workmux_config(repo_path)

    # Create the branch and then return to the default branch
    env.run_command(["git", "checkout", "-b", branch_name], cwd=repo_path)
    env.run_command(["git", "checkout", "main"], cwd=repo_path)

    # Manually create a git worktree for the branch to simulate the pre-existing state
    env.run_command(
        ["git", "worktree", "add", str(existing_worktree_path), branch_name],
        cwd=repo_path,
    )

    with pytest.raises(AssertionError) as excinfo:
        run_workmux_add(env, workmux_exe_path, repo_path, branch_name)

    stderr = str(excinfo.value)
    assert f"A worktree for branch '{branch_name}' already exists." in stderr
    assert "Use 'workmux open" in stderr


def test_add_copies_single_file(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies that `workmux add` copies a single file to the worktree."""
    env = isolated_tmux_server
    branch_name = "feature-copy-file"

    # Create a file in the repo root to copy
    env_file = repo_path / ".env"
    env_file.write_text("SECRET_KEY=test123")

    # Commit the file to avoid uncommitted changes
    env.run_command(["git", "add", ".env"], cwd=repo_path)
    env.run_command(["git", "commit", "-m", "Add .env file"], cwd=repo_path)

    # Configure workmux to copy the .env file
    write_workmux_config(repo_path, files={"copy": [".env"]}, env=env)

    worktree_path = add_branch_and_get_worktree(
        env, workmux_exe_path, repo_path, branch_name
    )
    assert_copied_file(worktree_path, ".env", "SECRET_KEY=test123")


def test_add_copies_multiple_files_with_glob(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies that `workmux add` copies multiple files using glob patterns."""
    env = isolated_tmux_server
    branch_name = "feature-copy-glob"

    # Create multiple .local files in the repo root
    (repo_path / ".env.local").write_text("LOCAL_VAR=value1")
    (repo_path / ".secrets.local").write_text("API_KEY=secret")

    # Commit the files
    env.run_command(["git", "add", "*.local"], cwd=repo_path)
    env.run_command(["git", "commit", "-m", "Add local files"], cwd=repo_path)

    # Configure workmux to copy all .local files
    write_workmux_config(repo_path, files={"copy": ["*.local"]}, env=env)

    worktree_path = add_branch_and_get_worktree(
        env, workmux_exe_path, repo_path, branch_name
    )
    assert_copied_file(worktree_path, ".env.local", "LOCAL_VAR=value1")
    assert_copied_file(worktree_path, ".secrets.local", "API_KEY=secret")


def test_add_copies_file_with_parent_directories(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies that `workmux add` creates parent directories when copying nested files."""
    env = isolated_tmux_server
    branch_name = "feature-copy-nested"

    # Create a nested file structure
    config_dir = repo_path / "config"
    config_dir.mkdir()
    (config_dir / "app.conf").write_text("setting=value")

    # Commit the files
    env.run_command(["git", "add", "config/"], cwd=repo_path)
    env.run_command(["git", "commit", "-m", "Add config files"], cwd=repo_path)

    # Configure workmux to copy the nested file
    write_workmux_config(repo_path, files={"copy": ["config/app.conf"]}, env=env)

    worktree_path = add_branch_and_get_worktree(
        env, workmux_exe_path, repo_path, branch_name
    )
    assert_copied_file(worktree_path, "config/app.conf", "setting=value")
    assert (worktree_path / "config").is_dir()


def test_add_symlinks_single_file(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies that `workmux add` creates a symlink for a single file."""
    env = isolated_tmux_server
    branch_name = "feature-symlink-file"

    # Create a file in the repo root to symlink
    shared_file = repo_path / "shared.txt"
    shared_file.write_text("shared content")

    # Commit the file
    env.run_command(["git", "add", "shared.txt"], cwd=repo_path)
    env.run_command(["git", "commit", "-m", "Add shared file"], cwd=repo_path)

    # Configure workmux to symlink the file
    write_workmux_config(repo_path, files={"symlink": ["shared.txt"]}, env=env)

    worktree_path = add_branch_and_get_worktree(
        env, workmux_exe_path, repo_path, branch_name
    )
    symlinked_file = assert_symlink_to(worktree_path, "shared.txt")
    assert symlinked_file.read_text() == "shared content"


def test_add_symlinks_directory(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies that `workmux add` creates a symlink for a directory."""
    env = isolated_tmux_server
    branch_name = "feature-symlink-dir"

    # Create a directory in the repo root to symlink
    node_modules = repo_path / "node_modules"
    node_modules.mkdir()
    (node_modules / "package.json").write_text('{"name": "test"}')

    # Commit the directory
    env.run_command(["git", "add", "node_modules/"], cwd=repo_path)
    env.run_command(["git", "commit", "-m", "Add node_modules"], cwd=repo_path)

    # Configure workmux to symlink the directory
    write_workmux_config(repo_path, files={"symlink": ["node_modules"]}, env=env)

    worktree_path = add_branch_and_get_worktree(
        env, workmux_exe_path, repo_path, branch_name
    )
    symlinked_dir = assert_symlink_to(worktree_path, "node_modules")
    assert (symlinked_dir / "package.json").exists()


def test_add_symlinks_multiple_items_with_glob(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies that `workmux add` creates symlinks for multiple items using glob patterns."""
    env = isolated_tmux_server
    branch_name = "feature-symlink-glob"

    # Create multiple cache directories
    (repo_path / ".cache").mkdir()
    (repo_path / ".cache" / "data.txt").write_text("cache data")
    (repo_path / ".pnpm-store").mkdir()
    (repo_path / ".pnpm-store" / "index.txt").write_text("pnpm index")

    # Commit the directories
    env.run_command(["git", "add", ".cache/", ".pnpm-store/"], cwd=repo_path)
    env.run_command(["git", "commit", "-m", "Add cache dirs"], cwd=repo_path)

    # Configure workmux to symlink using glob patterns
    write_workmux_config(repo_path, files={"symlink": [".*-store", ".cache"]}, env=env)

    worktree_path = add_branch_and_get_worktree(
        env, workmux_exe_path, repo_path, branch_name
    )
    cache_symlink = assert_symlink_to(worktree_path, ".cache")
    pnpm_symlink = assert_symlink_to(worktree_path, ".pnpm-store")
    assert (cache_symlink / "data.txt").exists()
    assert (pnpm_symlink / "index.txt").exists()


def test_add_symlinks_are_relative(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies that created symlinks use relative paths, not absolute paths."""
    env = isolated_tmux_server
    branch_name = "feature-symlink-relative"

    # Create a file to symlink
    test_file = repo_path / "test.txt"
    test_file.write_text("test content")

    # Commit the file
    env.run_command(["git", "add", "test.txt"], cwd=repo_path)
    env.run_command(["git", "commit", "-m", "Add test file"], cwd=repo_path)

    # Configure workmux to symlink the file
    write_workmux_config(repo_path, files={"symlink": ["test.txt"]}, env=env)

    worktree_path = add_branch_and_get_worktree(
        env, workmux_exe_path, repo_path, branch_name
    )
    symlinked_file = assert_symlink_to(worktree_path, "test.txt")

    # Verify the symlink points to the correct relative path
    source_file = repo_path / "test.txt"
    expected_target = os.path.relpath(source_file, symlinked_file.parent)
    link_target = os.readlink(symlinked_file)
    assert link_target == expected_target, (
        f"Symlink target incorrect. Expected: {expected_target}, Got: {link_target}"
    )


def test_add_symlink_replaces_existing_file(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies that symlinking replaces an existing file at the destination."""
    env = isolated_tmux_server
    branch_name = "feature-symlink-replace"

    # Create a file to symlink
    source_file = repo_path / "source.txt"
    source_file.write_text("source content")

    # Commit the file
    env.run_command(["git", "add", "source.txt"], cwd=repo_path)
    env.run_command(["git", "commit", "-m", "Add source file"], cwd=repo_path)

    # Configure workmux to symlink the file
    write_workmux_config(repo_path, files={"symlink": ["source.txt"]}, env=env)

    worktree_path = add_branch_and_get_worktree(
        env, workmux_exe_path, repo_path, branch_name
    )
    dest_file = worktree_path / "source.txt"

    # Remove the existing symlink and create a regular file
    dest_file.unlink()
    dest_file.write_text("replaced content")
    assert not dest_file.is_symlink()

    # Run workmux add again on a different branch to trigger symlink creation again
    # This simulates the --force-files behavior
    branch_name_2 = "feature-symlink-replace-2"
    worktree_path_2 = add_branch_and_get_worktree(
        env, workmux_exe_path, repo_path, branch_name_2
    )
    dest_file_2 = worktree_path_2 / "source.txt"
    assert dest_file_2.is_symlink()
    assert dest_file_2.read_text() == "source content"


def test_add_symlink_with_nested_structure(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies that symlinking works with nested directory structures."""
    env = isolated_tmux_server
    branch_name = "feature-symlink-nested"

    # Create a nested directory structure
    nested_dir = repo_path / "lib" / "cache"
    nested_dir.mkdir(parents=True)
    (nested_dir / "data.db").write_text("database content")

    # Commit the structure
    env.run_command(["git", "add", "lib/"], cwd=repo_path)
    env.run_command(["git", "commit", "-m", "Add nested structure"], cwd=repo_path)

    # Configure workmux to symlink the nested directory
    write_workmux_config(repo_path, files={"symlink": ["lib/cache"]}, env=env)

    worktree_path = add_branch_and_get_worktree(
        env, workmux_exe_path, repo_path, branch_name
    )
    symlinked_dir = assert_symlink_to(worktree_path, "lib/cache")
    assert (symlinked_dir / "data.db").read_text() == "database content"
    # Verify parent directory exists and is NOT a symlink
    assert (worktree_path / "lib").is_dir()
    assert not (worktree_path / "lib").is_symlink()


def test_add_combines_copy_and_symlink(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies that copy and symlink operations can be used together."""
    env = isolated_tmux_server
    branch_name = "feature-combined-ops"

    # Create files for both copy and symlink
    (repo_path / ".env").write_text("SECRET=abc123")
    node_modules = repo_path / "node_modules"
    node_modules.mkdir()
    (node_modules / "package.json").write_text('{"name": "test"}')

    # Commit both
    env.run_command(["git", "add", ".env", "node_modules/"], cwd=repo_path)
    env.run_command(["git", "commit", "-m", "Add files"], cwd=repo_path)

    # Configure workmux to both copy and symlink
    write_workmux_config(
        repo_path, files={"copy": [".env"], "symlink": ["node_modules"]}, env=env
    )

    worktree_path = add_branch_and_get_worktree(
        env, workmux_exe_path, repo_path, branch_name
    )

    assert_copied_file(worktree_path, ".env", "SECRET=abc123")
    symlinked_dir = assert_symlink_to(worktree_path, "node_modules")
    assert (symlinked_dir / "package.json").exists()


def test_add_file_operations_with_empty_config(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies that workmux add works when files config is empty or missing."""
    env = isolated_tmux_server
    branch_name = "feature-no-files"

    # Configure workmux with no file operations
    write_workmux_config(repo_path, env=env)

    # Should succeed without errors
    add_branch_and_get_worktree(env, workmux_exe_path, repo_path, branch_name)


def test_add_file_operations_with_nonexistent_pattern(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies that workmux handles glob patterns that match no files gracefully."""
    env = isolated_tmux_server
    branch_name = "feature-no-match"

    # Configure workmux with patterns that don't match anything
    write_workmux_config(
        repo_path,
        files={"copy": ["nonexistent-*.txt"], "symlink": ["missing-dir"]},
        env=env,
    )

    # Should succeed without errors (no matches is not an error)
    add_branch_and_get_worktree(env, workmux_exe_path, repo_path, branch_name)


def test_add_copy_with_path_traversal_fails(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies that `workmux add` fails if a copy path attempts to traverse outside the repo."""
    env = isolated_tmux_server
    branch_name = "feature-copy-traversal"

    # Create a sensitive file outside the repository
    (repo_path.parent / "sensitive_file").write_text("secret")

    write_workmux_config(repo_path, files={"copy": ["../sensitive_file"]}, env=env)

    with pytest.raises(AssertionError) as excinfo:
        run_workmux_add(env, workmux_exe_path, repo_path, branch_name)

    # The error should indicate path traversal or invalid path
    stderr = str(excinfo.value)
    assert (
        "Path traversal" in stderr
        or "outside" in stderr
        or "No such file" in stderr
        or "pattern matched nothing" in stderr
    )


def test_add_symlink_with_path_traversal_fails(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies that `workmux add` fails if a symlink path attempts to traverse outside the repo."""
    env = isolated_tmux_server
    branch_name = "feature-symlink-traversal"

    # Create a directory outside the repository that will be matched by the glob
    (repo_path.parent / "some_dir").mkdir()
    (repo_path.parent / "some_dir" / "file.txt").write_text("outside repo")

    write_workmux_config(repo_path, files={"symlink": ["../some_dir"]}, env=env)

    with pytest.raises(AssertionError) as excinfo:
        run_workmux_add(env, workmux_exe_path, repo_path, branch_name)

    # The error should indicate path traversal
    stderr = str(excinfo.value)
    assert "Path traversal" in stderr or "outside" in stderr


def test_add_symlink_overwrites_conflicting_file_from_git(
    isolated_tmux_server: TmuxEnvironment, workmux_exe_path: Path, repo_path: Path
):
    """Verifies a symlink operation overwrites a conflicting file checked out by git."""
    env = isolated_tmux_server
    branch_name = "feature-symlink-overwrite"

    # In main repo root, create the directory to be symlinked
    (repo_path / "node_modules").mkdir()
    (repo_path / "node_modules" / "dep.js").write_text("content")
    env.run_command(["git", "add", "node_modules/"], cwd=repo_path)
    env.run_command(["git", "commit", "-m", "Add real node_modules"], cwd=repo_path)

    # On a different branch, create a conflicting FILE with the same name
    env.run_command(["git", "checkout", "-b", "conflict-branch"], cwd=repo_path)
    env.run_command(["git", "rm", "-r", "node_modules"], cwd=repo_path)
    (repo_path / "node_modules").write_text("this is a placeholder file")
    env.run_command(["git", "add", "node_modules"], cwd=repo_path)
    env.run_command(["git", "commit", "-m", "Add conflicting file"], cwd=repo_path)

    # On main, configure workmux to symlink the directory
    env.run_command(["git", "checkout", "main"], cwd=repo_path)
    write_workmux_config(repo_path, files={"symlink": ["node_modules"]}, env=env)

    # Create a worktree from the branch with the conflicting file
    worktree_path = add_branch_and_get_worktree(
        env,
        workmux_exe_path,
        repo_path,
        branch_name,
        extra_args="--base conflict-branch",
    )

    symlinked_target = assert_symlink_to(worktree_path, "node_modules")
    assert (symlinked_target / "dep.js").exists()
